{% set version = "0.7.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-iptools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/iptools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/iptools/iptools_{{ version }}.tar.gz
  sha256: 19664df7822c6f105654f8f6b1a3fb9c441e5df51853f353d2adc04cf68b5fca

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-asioheaders
    - r-bh
    - r-rcpp >=0.11.2
    - r-readr
    - r-stringi
    - r-triebeard
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-asioheaders
    - r-bh
    - r-rcpp >=0.11.2
    - r-readr
    - r-stringi
    - r-triebeard

test:
  commands:
    - $R -e "library('iptools')"           # [not win]
    - "\"%R%\" -e \"library('iptools')\""  # [win]

about:
  home: https://github.com/hrbrmstr/iptools
  license: MIT
  summary: A toolkit for manipulating, validating and testing 'IP' addresses and ranges, along with datasets relating to 'IP' addresses. Tools are also provided to map 'IPv4' blocks to country codes. While it primarily has support for the 'IPv4' address space, more extensive 'IPv6' support is intended.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc

# Package: iptools
# Type: Package
# Title: Manipulate, Validate and Resolve 'IP' Addresses
# Version: 0.6.1
# Date: 2018-12-08
# Author: Bob Rudis <bob@rud.is> [aut, cre], Oliver Keyes <ironholds@gmail.com> [aut], Tim Smith [ctb]
# Maintainer: Bob Rudis <bob@rud.is>
# Description: A toolkit for manipulating, validating and testing 'IP' addresses and ranges, along with datasets relating to 'IP' addresses. Tools are also provided to map 'IPv4' blocks to country codes. While it primarily has support for the 'IPv4' address space, more extensive 'IPv6' support is intended.
# License: MIT + file LICENSE
# URL: https://github.com/hrbrmstr/iptools
# BugReports: https://github.com/hrbrmstr/iptools/issues
# NeedsCompilation: yes
# SystemRequirements: C++11
# Depends: R (>= 3.0.0)
# Suggests: testthat, knitr, rmarkdown
# Imports: Rcpp (>= 0.11.2), utils, stats, AsioHeaders, stringi, readr, triebeard
# Encoding: UTF-8
# LinkingTo: BH, Rcpp, AsioHeaders
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1.9000
# Packaged: 2018-12-08 14:53:10 UTC; bob
# Repository: CRAN
# Date/Publication: 2018-12-09 14:40:02 UTC
