travis:
  secure:
    BINSTAR_TOKEN: qpkRk6IwsbS6NaFbuh5LDo0ev102qB2Wacvpi9QlB+mqk37B4VHpo+04PyQ2seZSth7EaNxoP/ISZ81hYgfQ6VE/MOXH+bZGQAl6YrElzRoro+01OnIS59yZvPw+5xjFt/lsvVeRuHcK3vcPFHIt3MFjPnAxnTi58h3gn7gXXbN+4cMh7cGzoHscEk3Evs5ugSzfaHXs99A2t6uQxybSMfk1/eDifCZWU3M2WgmrwrHweaLa07u4orXG7prwGVFH2PdXG1wcqbH+lnIUbcX1jcfLuKRdTdsnjvbEBwfyQsW99brinrGxT1S5BhgxG8ImWL3BFKqLRIFKMVwJkh6yynUlR8syNdw0VK2/bIMiti+NU8HxpVzHBgT3mJgzG+VVVSfmIh/Yq4bvrIpJRLgIKb2P1m2hyizBLK+lChIJ3yATz4bqsQ7vlxvqvFz2SjSKEabMlxwyAQIrVS7Fquf8L+4FcUGwyC63gEEtJoBMhUIqA9/TYrlx1kRzfBcLPcXezr7UDiHQKXVGFwgbRIP/51NX/peoZXf7grwy3u/Ym7HMW/Ii7wcK+HNIq1OJJ8exoLNOhP9l9kTjsUoQXzwM3F9laabOCBPHZfJGz4D6MSRWIJaMcLoLGfoXCAdrQTPacP4lafbu9sY5ExnRsqkGBKt1E22Js+AOyht1PmtlFZI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
